{
 "title": "Awair",
 "tags": [ "awair" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "device",
    "label": "Awair Device",
    "query": {
     "query": "label_values(awair_exporter_device_name)"
    }
   },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Awair Score",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "awair_score", "legendFormat": "{{awair_exporter_device_name}}" }
   ]
  },
  {
   "title": "Awair Score",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "quantile(0.5, awair_score{awair_exporter_device_name=~\"$device\"}) by (awair_exporter_device_name)",
     "legendFormat": "{{awair_exporter_device_name}}"
    }
   ]
  },
  {
   "title": "Carbon Dioxide (ppm)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "quantile(0.5, awair_co2{awair_exporter_device_name=~\"$device\"}) by (awair_exporter_device_name)",
     "legendFormat": "{{awair_exporter_device_name}}"
    }
   ]
  },
  {
   "title": "Total Volatile Organic Compounds (ppb)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "quantile(0.5, awair_voc{awair_exporter_device_name=~\"$device\"}) by (awair_exporter_device_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Particulate Matter < 2.5 microns",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "quantile(0.5, awair_pm25{awair_exporter_device_name=~\"$device\"}) by (awair_exporter_device_name)",
     "legendFormat": "{{awair_exporter_device_name}}"
    }
   ]
  },
  {
   "title": "Temperature (°F)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "quantile(0.5, (awair_temp{awair_exporter_device_name=~\"$device\"} * 9/5) + 32) by (awair_exporter_device_name)",
     "legendFormat": "{{awair_exporter_device_name}}"
    }
   ]
  },
  {
   "title": "Humidity (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "quantile(0.5, awair_humidity{awair_exporter_device_name=~\"$device\"}) by (awair_exporter_device_name)",
     "legendFormat": "{{awair_exporter_device_name}}"
    }
   ]
  },
  {
   "title": "Device Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    { "expr": "awair_device_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Exporter Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    { "expr": "awair_exporter_info", "legendFormat": "{{label_name}}" }
   ]
  }
 ]
}