{
 "title": "Spotify Moderator",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Playlist Remote Reconciles",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(spotify_sentry_playlists_reconciled_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reconciliations by Playlist",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(spotify_sentry_playlists_reconciled_total[$__range])) by (playlist_id)",
     "legendFormat": "{{playlist_id}}"
    }
   ]
  },
  {
   "title": "Playlist Local Updates",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(spotify_sentry_playlists_updated_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Updates by Playlist",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(spotify_sentry_playlists_updated_total[$__range])) by (playlist_id)",
     "legendFormat": "{{playlist_id}}"
    }
   ]
  },
  {
   "title": "Playlist Reconciliations",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{k8s_app=\"spotify-sentry\"} |= `Playlist needs reconciliation`"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "{k8s_app=\"spotify-sentry\"} |= `` | json level=\"level\", playlist_id=\"playlist_id\""
    }
   ]
  }
 ]
}