{
 "title": "Speedtest",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Download",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(sponsor, url) (speedtest_download_speed_mbps)",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Speedtest Download (mbps)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "avg by(sponsor, url) (speedtest_download_speed_mbps)",
     "legendFormat": "{{sponsor}}"
    }
   ]
  },
  {
   "title": "Test Duration",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(job) (speedtest_test_duration_ms)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(sponsor, url) (speedtest_upload_speed_mbps)",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Speedtest Upload",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "avg by(sponsor, url) (speedtest_upload_speed_mbps)",
     "legendFormat": "{{sponsor}}"
    }
   ]
  },
  {
   "title": "Speedtest Latency",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(sponsor, url) (speedtest_latency_ms)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Speedtest Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(sponsor, url) (speedtest_latency_ms)",
     "legendFormat": "{{sponsor}}"
    }
   ]
  },
  {
   "title": "Tests",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{k8s_instance=\"prometheus-speedtest-exporter\"} |= `Updated Results` | json result=\"results[0]\""
    }
   ]
  },
  {
   "title": "Exporter Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "targets": [
    { "expr": "speedtest_exporter_info", "legendFormat": "__auto" }
   ]
  }
 ]
}