{
 "title": "EdgeRouter (SNMP)",
 "description": "EdgeRouter Dashboard",
 "tags": [
  "snmp",
  "edgerouter"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(hrSystemUptime, instance)"
    }
   },
   {
    "name": "interface",
    "label": "LAN Interface",
    "query": {
     "query": "label_values(ifHCInOctets{ifName=~\"eth[1-9].*|wg[0-9].*\"}, ifName)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(hrSystemUptime / 100) by (target, instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "eth0 Rx",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(irate(ifHCInOctets{ifName=\"eth0\"}[5m]) * 8) by (target, instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "eth0 Tx",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(irate(ifHCOutOctets{ifName=\"eth0\"}[5m]) * 8) by (target,instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "100 - ssCpuIdle", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "RAM",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "memAvailReal / memTotalReal * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "WAN Download",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ifHCInOctets{ifName=\"eth0\"}[${__range}]@${__to:date:seconds})) by (target,instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "eth0 Download",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 21, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "avg(irate(ifHCInOctets{ifName=\"eth0\"}[5m]) * 8) by (target,instance)",
     "legendFormat": "Download({{target}}, {{instance}}, {{ifName}})"
    },
    {
     "expr": "avg(irate(ifHCOutOctets{ifName=\"eth0\"}[5m]) * -8) by (target,instance)",
     "legendFormat": "Upload({{target}}, {{instance}}, {{ifName}})"
    }
   ]
  },
  {
   "title": "WAN Upload",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ifHCOutOctets{ifName=\"eth0\"}[${__range}]@${__to:date:seconds})) by (target,instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "${interface}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }, "repeat": "interface" },
  {
   "title": "${interface} RX",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ifHCInOctets{ifName=\"${interface:raw}\"}[${__range}]@${__to:date:seconds})) by (target,instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "${interface} Download",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 21, "x": 3, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "avg(irate(ifHCInOctets{ifName=\"${interface:raw}\"}[5m]) * 8) by (target,instance, ifName)",
     "legendFormat": "RX({{target}}, {{instance}}, {{ifName}})"
    },
    {
     "expr": "avg(irate(ifHCOutOctets{ifName=\"${interface:raw}\"}[5m]) * -8) by (target,instance, ifName)",
     "legendFormat": "TX({{target}}, {{instance}}, {{ifName}})"
    }
   ]
  },
  {
   "title": "${interface} TX",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ifHCOutOctets{ifName=\"${interface:raw}\"}[${__range}]@${__to:date:seconds})) by (target,instance)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}