{
 "title": "Blocky Dev",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "ds", "label": "Data Source", "query": "prometheus" },
   { "name": "psds", "query": "postgres" }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(blocky_query_total[$__range]))",
     "legendFormat": "Total Queries"
    },
    { "expr": "avg(blocky_cache_entry_count)", "legendFormat": "Cache Size" },
    {
     "expr": "sum(increase(blocky_cache_hit_count[$__range]))",
     "legendFormat": "Cache Hits"
    },
    {
     "expr": "sum(increase(blocky_cache_miss_count[$__range]))",
     "legendFormat": "Cache Miss"
    },
    {
     "expr": "sum(blocky_prefetch_domain_name_cache_count)",
     "legendFormat": "Prefetch Cache Size"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(time() - container_start_time_seconds{container=\"blocky\"})",
     "legendFormat": "Uptime"
    },
    {
     "expr": "sum(container_threads{container=\"blocky\"})",
     "legendFormat": "Threads"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(blocky_request_duration_ms_bucket[5m])) by (le))",
     "legendFormat": "Median Lookup"
    },
    {
     "expr": "avg(time() - blocky_last_list_group_refresh)",
     "legendFormat": "Last List Refresh"
    },
    { "expr": "sum(blocky_error_total)", "legendFormat": "Errors" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"blocky\"})",
     "legendFormat": "State"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(blocky_blocking_enabled)", "legendFormat": "Blocking" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(group) (blocky_blacklist_cache{group=\"ads\"})",
     "legendFormat": "Blocklist Domains"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(blocky_response_total{response_type=\"CACHED\"}[$__range])) + sum(increase(blocky_response_total{response_type=\"BLOCKED\"}[$__range]))) / sum(increase(blocky_response_total[$__range]))",
     "legendFormat": "Cache Hit"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(blocky_prefetch_count[$__range]))",
     "legendFormat": "Prefetched Responses"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(blocky_response_total{response_type=\"RESOLVED\"}[$__range])) / sum(increase(blocky_response_total[$__range]))",
     "legendFormat": "Cache Miss"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(blocky_prefetch_count) / sum(blocky_query_total)",
     "legendFormat": "Prefetch Response Rate"
    }
   ]
  },
  {
   "title": "Request Latency (ms)",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(blocky_request_duration_ms_bucket[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(blocky_request_duration_ms_bucket{response_type =~\"CACHED|BLOCKED\"}) by (le))",
     "legendFormat": "CACHED|BLOCKED"
    },
    {
     "expr": "histogram_quantile(0.95, sum(blocky_request_duration_ms_bucket{response_type !~\"CACHED|BLOCKED\"}) by (le))",
     "legendFormat": "RESOLVED"
    }
   ]
  },
  {
   "title": "Queries by Type",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(blocky_query_total[$__range])) by (type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Responses",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(blocky_response_total[$__range])) by (response_code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Type",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(blocky_response_total[$__range])) by (response_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(request_ts, $__interval),\n  client_name as metric,\n  COUNT(*) as value\nFROM\n  log_entries\nWHERE\n  $__timeFilter(request_ts)\nGROUP BY\n  1,\n  2\nORDER BY\n  1,\n  2 asc"
    }
   ]
  },
  {
   "title": "Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum(increase(blocky_response_total[$__interval])) by (response_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Live Clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(request_ts, $__interval),\n  COUNT(DISTINCT client_ip) as clients\nFROM\n  log_entries\nWHERE\n  $__timeFilter(request_ts)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Top Client Queries",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "rawSql": "SELECT\n    client_name,\n    question_type,\n    question_name,\n    count(*) as cnt\nFROM \n  log_entries\nWHERE\n  $__timeFilter(request_ts) \nGROUP BY\n  client_name,\n  question_name,\n  question_type\nORDER BY cnt desc\nLIMIT 20;"
    }
   ]
  },
  {
   "title": "Top Blocked",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "rawSql": "SELECT\n    question_name,\n    question_type,\n    count(*) as cnt\nFROM \n  log_entries\nWHERE\n  response_type = 'BLOCKED' AND\n  $__timeFilter(request_ts) \nGROUP BY\n  client_name,\n  question_name,\n  question_type\nORDER BY cnt desc\nLIMIT 20;"
    }
   ]
  },
  {
   "title": "Live Queries",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "rawSql": "SELECT\n  client_name,\n  question_name,\n  question_type,\n  duration_ms,\n  request_ts,\n  response_code,\n  reason\nFROM\n  log_entries\nWHERE\n  $__timeFilter(request_ts) \nORDER BY\n  request_ts DESC\nlimit 50;\n"
    }
   ]
  },
  {
   "title": "Live Blocked",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "rawSql": "SELECT\n  client_name,\n  question_name,\n  question_type,\n  request_ts\nFROM\n  log_entries\nWHERE\n  $__timeFilter(request_ts) AND\n  response_type = 'BLOCKED'\nORDER BY\n  request_ts DESC\nlimit 50;\n"
    }
   ]
  }
 ]
}